### ISSUE TITLE
New Feature - Host the website using github pages

### ISSUE THREAD

**Issue by rampa2510** [YashMeh/panda-portfolio#15]
We can add a feature to host the website using GitHub pages after the user has created the page with the user's consent?

**Comment by bhumijgupta** [comment]
That would be a great feature to add, but it would limit the feature exclusively for Github users. Whereas we wanted to make the npm module for everyone irrespective of the mode of deployment of website.
Tagging @YashMeh for future discussions

**Comment by rampa2510** [comment]
There is a package for using the GitHub API ocktokit/rest so we will have to create the repository with the name <github-username>.github.io and that's it

**Comment by rampa2510** [comment]
> That would be a great feature to add, but it would limit the feature exclusively for Github users. Whereas we wanted to make the npm module for everyone irrespective of the mode of deployment of website.
> Tagging @YashMeh for future discussions

Hey we can make this optional like asking the user whether they want to use it or not

**Comment by YashMeh** [comment]
> There is a package for using the GitHub API ocktokit/rest so we will have to create the repository with the name **_github-username.github.io_** and that's it Also everytime they manually update it we can create a new command for the updation? Any other ideas?

But anyway you create a <i>username.github.io</i> and create an index.html inside it,it will host automatically.

**Comment by rampa2510** [comment]
Yes it will I didn't get the point?

**Comment by YashMeh** [comment]
Kindly attach the steps you are proposing to follow :)

**Comment by rampa2510** [comment]
1) I would add the ocktokit/res package to communicate with the github API
2) Then every time the user creates the portfolio file we can ask them whether they want to host the website using github pages?
3) If yes then we will ask for creds, create the repository with the name username.github.io and push the file in this repo.

**Comment by YashMeh** [comment]
Sorry for the late reply ..
What if I have an existing page hosted at username.github.io, then will there be a conflict or over-writing ?
In case I want to host the pages at a different namespace username.github.io/portfolio ?

**Comment by rampa2510** [comment]
I think that most of the time when users create a portfolio page they keep the file in the root directory so this case would be a rare one. But again as I mentioned we can give them the option to opt out and manually host it.

**Comment by YashMeh** [comment]
LGTM lets work on it .. :)

**Comment by rampa2510** [comment]
Please update the readme after reviewing the pull request

**Comment by YashMeh** [comment]
closed via #23
